name: Build IPQ807x
on: [push]

jobs:
    build:
        name: Prepare and build IPQ807x generic images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Update and install feeds
              run: |
                ./scripts/feeds update -a
                ./scripts/feeds install -a

            - name: Generate config for IPQ807x Generic
              run: |
                echo CONFIG_TARGET_ipq807x=y > .config
                echo CONFIG_TARGET_ipq807x_generic=y >> .config
                echo CONFIG_TARGET_MULTI_PROFILE=y >> .config
                echo CONFIG_TARGET_ALL_PROFILES=y >> .config
                echo CONFIG_TARGET_PER_DEVICE_ROOTFS=y >> .config
                echo CONFIG_TARGET_ROOTFS_INITRAMFS=y >> .config
                echo CONFIG_TARGET_INITRAMFS_COMPRESSION_ZSTD=y >> .config
                echo CONFIG_PACKAGE_luci=y >> .config
                echo CONFIG_PACKAGE_kmod-qca-nss-dp=y >> .config
                echo CONFIG_PACKAGE_qca-ssdk-shell=y >> .config
                echo CONFIG_TARGET_ipq807x_generic_DEVICE_xiaomi_ax3600=y >> .config
                echo CONFIG_HAS_SUBTARGETS=y >> .config
                echo CONFIG_TARGET_BOARD="ipq807x" >> .config
                echo CONFIG_TARGET_SUBTARGET="generic" >> .config
                echo CONFIG_TARGET_PROFILE="DEVICE_xiaomi_ax3600" >> .config
                echo CONFIG_TARGET_ARCH_PACKAGES="aarch64_cortex-a53" >> .config
                echo CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe -mcpu=cortex-a53" >> .config
                echo CONFIG_TARGET_ROOTFS_SQUASHFS=y >> .config
                echo CONFIG_TARGET_SQUASHFS_BLOCK_SIZE=256 >> .config
                echo CONFIG_TARGET_UBIFS_FREE_SPACE_FIXUP=y >> .config
                echo CONFIG_TARGET_OPTIMIZATION="-Os -pipe -mcpu=cortex-a53" >> .config
                echo CONFIG_TARGET_SUFFIX="musl" >> .config
                echo CONFIG_PACKAGE_nss-firmware-ipq8074=y >> .config
                echo CONFIG_PACKAGE_kmod-qca-nss-dp=y >> .config
                echo CONFIG_PACKAGE_luci-theme-material=y >> .config

                make defconfig

            - name: Download package sources
              run: make download V=s

            - name: Build tools
              run: |
                make tools/install -j$(nproc) V=s || \
                make tools/install V=s

            - name: Build toolchain
              run: |
                make toolchain/install -j$(nproc) V=s || \
                make toolchain/install V=s

            - name: Build target images
              run: |
                make -j$(nproc) V=s || \
                make V=s

            - name: TAR output
              run: tar -cvf ipq807xx-images.tar bin/targets/ipq807x/generic

            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                name: ipq807x-images
                path: ipq807xx-images.tar

    release:
          name: Make a release
          runs-on: ubuntu-latest
          needs: build

          steps:
            - name: Download the image artifacts
              uses: actions/download-artifact@v2
              with:
                name: ipq807x-images

            - name: Extract the image artifacts
              run: tar xf ipq807xx-images.tar

            - name: Create a release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}"
                prerelease: true
                title: "Updated prebuilt images"
                automatic_release_tag: "ipq807x-latest"
                files: bin/targets/ipq807x/generic/*
